import type { Metadata } from 'next'
import '../styles/main.scss'
import { Header } from '@/components/layout/Header/Header'

export const metadata: Metadata = {
	title: 'Test task',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	)
}
