import type { Metadata } from 'next'
import '../styles/main.scss'
import { Header } from '@/components/layout/Header/Header'
import { AppProvider } from '@/components/layout/context/AppProvider'

export const metadata: Metadata = {
	title: 'Test task',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body>
				<AppProvider>
					<Header />
					<main>{children}</main>
				</AppProvider>
			</body>
		</html>
	)
}
